<?php

namespace AppBundle\Repository;

/**
 * ChoferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoferRepository extends \Doctrine\ORM\EntityRepository
{
//    function __construct()
//    {
//    }

    public function findByIdTrabajador($id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT chofer.* FROM chofer WHERE chofer.trabajador_id= :id')->setParameter('id', $id);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
//        return parent::find($id, $lockMode, $lockVersion); // TODO: Change the autogenerated stub
    }
//
//    public function find($id, $lockMode = null, $lockVersion = null)
//    {
//        return parent::find($id, $lockMode, $lockVersion); // TODO: Change the autogenerated stub
//    }
//
//    public function findAll()
//    {
//        return parent::findAll(); // TODO: Change the autogenerated stub
//    }
//
//    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
//    {
//        return parent::findBy($criteria, $orderBy, $limit, $offset); // TODO: Change the autogenerated stub
//    }
//
//    public function findOneBy(array $criteria, array $orderBy = null)
//    {
//        return parent::findOneBy($criteria, $orderBy); // TODO: Change the autogenerated stub
//    }

}
