<?php

namespace AppBundle\Repository;

/**
 * DiasSemanaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiasSemanaRepository extends \Doctrine\ORM\EntityRepository
{
}
