<?php

namespace AppBundle\Repository;

/**
 * EscogidaTurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscogidaTurnoRepository extends \Doctrine\ORM\EntityRepository
{
}
