<?php

namespace AppBundle\Repository;

/**
 * OmnibusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OmnibusRepository extends \Doctrine\ORM\EntityRepository
{
}
