<?php

namespace AppBundle\Repository;

/**
 * RutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutaRepository extends \Doctrine\ORM\EntityRepository
{
}
