<?php

namespace AppBundle\Repository;

/**
 * Tarjeta_combustibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tarjeta_combustibleRepository extends \Doctrine\ORM\EntityRepository
{
}
