<?php

namespace AppBundle\Repository;

/**
 * TestTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestTestRepository extends \Doctrine\ORM\EntityRepository
{
}
