<?php

namespace AppBundle\Repository;

/**
 * TipoIncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoIncidenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
