<?php

namespace App\Repository;

/**
 * ChoferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoferRepository extends \Doctrine\ORM\EntityRepository
{
}
