<?php

namespace App\Repository;

/**
 * CombustibleHabilitadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CombustibleHabilitadoRepository extends \Doctrine\ORM\EntityRepository
{
}
