<?php

namespace App\Repository;

/**
 * HojaRutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojaRutaRepository extends \Doctrine\ORM\EntityRepository
{
}
