<?php

namespace App\Repository;

/**
 * Incidencia_HRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Incidencia_HRRepository extends \Doctrine\ORM\EntityRepository
{
}
