<?php

namespace App\Repository;

/**
 * Pto_expedicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pto_expedicionRepository extends \Doctrine\ORM\EntityRepository
{
}
