<?php

namespace App\Repository;

/**
 * TipoCombustibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCombustibleRepository extends \Doctrine\ORM\EntityRepository
{
}
