<?php

namespace App\Repository;

/**
 * Tipo_omnibusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo_omnibusRepository extends \Doctrine\ORM\EntityRepository
{
}
