<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EscogidaTurno extends \AppBundle\Entity\EscogidaTurno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'empieza', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'sale', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'termina', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'cantidadViajes', 'ruta', 'chofer', 'omnibus', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'turno', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'trabajaHoras', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'descansoDias', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'descansoComienza', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'descansoTermina', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'periodoEscogida');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'empieza', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'sale', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'termina', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'cantidadViajes', 'ruta', 'chofer', 'omnibus', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'turno', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'trabajaHoras', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'descansoDias', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'descansoComienza', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'descansoTermina', '' . "\0" . 'AppBundle\\Entity\\EscogidaTurno' . "\0" . 'periodoEscogida');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EscogidaTurno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addRuta(\AppBundle\Entity\Ruta $ruta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRuta', array($ruta));

        return parent::addRuta($ruta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRuta(\AppBundle\Entity\Ruta $ruta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRuta', array($ruta));

        return parent::removeRuta($ruta);
    }

    /**
     * {@inheritDoc}
     */
    public function addChofer(\AppBundle\Entity\Chofer $chofer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChofer', array($chofer));

        return parent::addChofer($chofer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChofer(\AppBundle\Entity\Chofer $chofer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChofer', array($chofer));

        return parent::removeChofer($chofer);
    }

    /**
     * {@inheritDoc}
     */
    public function addOmnibus(\AppBundle\Entity\Omnibus $omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOmnibus', array($omnibus));

        return parent::addOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOmnibus(\AppBundle\Entity\Omnibus $omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOmnibus', array($omnibus));

        return parent::removeOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function addRutum(\AppBundle\Entity\Ruta $rutum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRutum', array($rutum));

        return parent::addRutum($rutum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRutum(\AppBundle\Entity\Ruta $rutum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRutum', array($rutum));

        return parent::removeRutum($rutum);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadViajes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadViajes', array());

        return parent::getCantidadViajes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadViajes($cantidadViajes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadViajes', array($cantidadViajes));

        return parent::setCantidadViajes($cantidadViajes);
    }

    /**
     * {@inheritDoc}
     */
    public function getChofer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChofer', array());

        return parent::getChofer();
    }

    /**
     * {@inheritDoc}
     */
    public function setChofer($chofer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChofer', array($chofer));

        return parent::setChofer($chofer);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescansoComienza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescansoComienza', array());

        return parent::getDescansoComienza();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescansoComienza($descansoComienza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescansoComienza', array($descansoComienza));

        return parent::setDescansoComienza($descansoComienza);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescansoDias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescansoDias', array());

        return parent::getDescansoDias();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescansoDias($descansoDias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescansoDias', array($descansoDias));

        return parent::setDescansoDias($descansoDias);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescansoTermina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescansoTermina', array());

        return parent::getDescansoTermina();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescansoTermina($descansoTermina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescansoTermina', array($descansoTermina));

        return parent::setDescansoTermina($descansoTermina);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpieza()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpieza', array());

        return parent::getEmpieza();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpieza($empieza)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpieza', array($empieza));

        return parent::setEmpieza($empieza);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmnibus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmnibus', array());

        return parent::getOmnibus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmnibus($omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmnibus', array($omnibus));

        return parent::setOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuta', array());

        return parent::getRuta();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuta($ruta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuta', array($ruta));

        return parent::setRuta($ruta);
    }

    /**
     * {@inheritDoc}
     */
    public function getSale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSale', array());

        return parent::getSale();
    }

    /**
     * {@inheritDoc}
     */
    public function setSale($sale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSale', array($sale));

        return parent::setSale($sale);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermina', array());

        return parent::getTermina();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermina($termina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermina', array($termina));

        return parent::setTermina($termina);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajaHoras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajaHoras', array());

        return parent::getTrabajaHoras();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrabajaHoras($trabajaHoras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrabajaHoras', array($trabajaHoras));

        return parent::setTrabajaHoras($trabajaHoras);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurno', array());

        return parent::getTurno();
    }

    /**
     * {@inheritDoc}
     */
    public function setTurno($turno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurno', array($turno));

        return parent::setTurno($turno);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoEscogida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoEscogida', array());

        return parent::getPeriodoEscogida();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoEscogida($periodoEscogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoEscogida', array($periodoEscogida));

        return parent::setPeriodoEscogida($periodoEscogida);
    }

}
