<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Incidencia extends \AppBundle\Entity\Incidencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Incidencia' . "\0" . 'idincidencia', '' . "\0" . 'AppBundle\\Entity\\Incidencia' . "\0" . 'detalles', 'tipoIncidencia', 'incidencia_hr');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Incidencia' . "\0" . 'idincidencia', '' . "\0" . 'AppBundle\\Entity\\Incidencia' . "\0" . 'detalles', 'tipoIncidencia', 'incidencia_hr');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Incidencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addIncidencias_HR(\AppBundle\Entity\Incidencias_HR $incidencia_hr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIncidencias_HR', array($incidencia_hr));

        return parent::addIncidencias_HR($incidencia_hr);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIncidencias_HR(\AppBundle\Entity\Incidencias_HR $incidencia_hr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIncidencias_HR', array($incidencia_hr));

        return parent::removeIncidencias_HR($incidencia_hr);
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalles($detalles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalles', array($detalles));

        return parent::setDetalles($detalles);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalles', array());

        return parent::getDetalles();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdincidencia()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdincidencia();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdincidencia', array());

        return parent::getIdincidencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdincidencia($idincidencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdincidencia', array($idincidencia));

        return parent::setIdincidencia($idincidencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncidenciaHr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncidenciaHr', array());

        return parent::getIncidenciaHr();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncidenciaHr($incidencia_hr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncidenciaHr', array($incidencia_hr));

        return parent::setIncidenciaHr($incidencia_hr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoIncidencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoIncidencia', array());

        return parent::getTipoIncidencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoIncidencia($tipoIncidencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoIncidencia', array($tipoIncidencia));

        return parent::setTipoIncidencia($tipoIncidencia);
    }

}
