<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Omnibus extends \AppBundle\Entity\Omnibus implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'chapa', 'chofer', 'typeOmnibus', 'gps', 'base', 'tarjetaCombustible', 'escogida', 'hojaRuta', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'noOmnibus', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'indiceConsumoReal', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'kmRecorridosAcumulados', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'marca', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'licenciaOperativaEmision', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'licenciaOperativaVencimiento', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'FICAV_emision', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'FICAV_vencimiento', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'mantenimiento', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'en_revision', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'is_roto');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'chapa', 'chofer', 'typeOmnibus', 'gps', 'base', 'tarjetaCombustible', 'escogida', 'hojaRuta', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'noOmnibus', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'indiceConsumoReal', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'kmRecorridosAcumulados', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'marca', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'licenciaOperativaEmision', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'licenciaOperativaVencimiento', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'FICAV_emision', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'FICAV_vencimiento', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'mantenimiento', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'en_revision', '' . "\0" . 'AppBundle\\Entity\\Omnibus' . "\0" . 'is_roto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Omnibus $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addChofer(\AppBundle\Entity\Chofer $chofer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChofer', array($chofer));

        return parent::addChofer($chofer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChofer(\AppBundle\Entity\Chofer $chofer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChofer', array($chofer));

        return parent::removeChofer($chofer);
    }

    /**
     * {@inheritDoc}
     */
    public function addGp(\AppBundle\Entity\GPS $gp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGp', array($gp));

        return parent::addGp($gp);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGp(\AppBundle\Entity\GPS $gp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGp', array($gp));

        return parent::removeGp($gp);
    }

    /**
     * {@inheritDoc}
     */
    public function addEscogida(\AppBundle\Entity\EscogidaTurno $escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEscogida', array($escogida));

        return parent::addEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEscogida(\AppBundle\Entity\EscogidaTurno $escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEscogida', array($escogida));

        return parent::removeEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function addHojaRutum(\AppBundle\Entity\HojaRuta $hojaRutum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHojaRutum', array($hojaRutum));

        return parent::addHojaRutum($hojaRutum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHojaRutum(\AppBundle\Entity\HojaRuta $hojaRutum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHojaRutum', array($hojaRutum));

        return parent::removeHojaRutum($hojaRutum);
    }

    /**
     * {@inheritDoc}
     */
    public function getFICAVEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFICAVEmision', array());

        return parent::getFICAVEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setFICAVEmision($FICAV_emision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFICAVEmision', array($FICAV_emision));

        return parent::setFICAVEmision($FICAV_emision);
    }

    /**
     * {@inheritDoc}
     */
    public function getFICAVVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFICAVVencimiento', array());

        return parent::getFICAVVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFICAVVencimiento($FICAV_vencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFICAVVencimiento', array($FICAV_vencimiento));

        return parent::setFICAVVencimiento($FICAV_vencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getBase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBase', array());

        return parent::getBase();
    }

    /**
     * {@inheritDoc}
     */
    public function setBase($base)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBase', array($base));

        return parent::setBase($base);
    }

    /**
     * {@inheritDoc}
     */
    public function getChapa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChapa', array());

        return parent::getChapa();
    }

    /**
     * {@inheritDoc}
     */
    public function setChapa($chapa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChapa', array($chapa));

        return parent::setChapa($chapa);
    }

    /**
     * {@inheritDoc}
     */
    public function getChofer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChofer', array());

        return parent::getChofer();
    }

    /**
     * {@inheritDoc}
     */
    public function setChofer($chofer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChofer', array($chofer));

        return parent::setChofer($chofer);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnRevision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnRevision', array());

        return parent::isEnRevision();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnRevision($en_revision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnRevision', array($en_revision));

        return parent::setEnRevision($en_revision);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscogida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscogida', array());

        return parent::getEscogida();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscogida($escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscogida', array($escogida));

        return parent::setEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function getGps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGps', array());

        return parent::getGps();
    }

    /**
     * {@inheritDoc}
     */
    public function setGps($gps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGps', array($gps));

        return parent::setGps($gps);
    }

    /**
     * {@inheritDoc}
     */
    public function getHojaRuta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHojaRuta', array());

        return parent::getHojaRuta();
    }

    /**
     * {@inheritDoc}
     */
    public function setHojaRuta($hojaRuta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHojaRuta', array($hojaRuta));

        return parent::setHojaRuta($hojaRuta);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndiceConsumoReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndiceConsumoReal', array());

        return parent::getIndiceConsumoReal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndiceConsumoReal($indiceConsumoReal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndiceConsumoReal', array($indiceConsumoReal));

        return parent::setIndiceConsumoReal($indiceConsumoReal);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsRoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsRoto', array());

        return parent::isIsRoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRoto($is_roto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRoto', array($is_roto));

        return parent::setIsRoto($is_roto);
    }

    /**
     * {@inheritDoc}
     */
    public function getKmRecorridosAcumulados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKmRecorridosAcumulados', array());

        return parent::getKmRecorridosAcumulados();
    }

    /**
     * {@inheritDoc}
     */
    public function setKmRecorridosAcumulados($kmRecorridosAcumulados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKmRecorridosAcumulados', array($kmRecorridosAcumulados));

        return parent::setKmRecorridosAcumulados($kmRecorridosAcumulados);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenciaOperativaEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenciaOperativaEmision', array());

        return parent::getLicenciaOperativaEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenciaOperativaEmision($licenciaOperativaEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenciaOperativaEmision', array($licenciaOperativaEmision));

        return parent::setLicenciaOperativaEmision($licenciaOperativaEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenciaOperativaVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenciaOperativaVencimiento', array());

        return parent::getLicenciaOperativaVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenciaOperativaVencimiento($licenciaOperativaVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenciaOperativaVencimiento', array($licenciaOperativaVencimiento));

        return parent::setLicenciaOperativaVencimiento($licenciaOperativaVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function isMantenimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isMantenimiento', array());

        return parent::isMantenimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setMantenimiento($mantenimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMantenimiento', array($mantenimiento));

        return parent::setMantenimiento($mantenimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', array());

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', array($marca));

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoOmnibus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoOmnibus', array());

        return parent::getNoOmnibus();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoOmnibus($noOmnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoOmnibus', array($noOmnibus));

        return parent::setNoOmnibus($noOmnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarjetaCombustible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarjetaCombustible', array());

        return parent::getTarjetaCombustible();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarjetaCombustible($tarjetaCombustible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarjetaCombustible', array($tarjetaCombustible));

        return parent::setTarjetaCombustible($tarjetaCombustible);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeOmnibus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeOmnibus', array());

        return parent::getTypeOmnibus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeOmnibus($typeOmnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeOmnibus', array($typeOmnibus));

        return parent::setTypeOmnibus($typeOmnibus);
    }

}
