<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HojaRuta extends \AppBundle\Entity\HojaRuta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'NoHojaRuta', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'basico', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'conIncremento', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'turnopartido', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'confronta', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'voluntario', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'totalHoras', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'cantidadViajes', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'cantidadSalidas', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'fecha', 'turno', 'omnibus', 'recaudaciones', 'ruta', 'incidencia_hr');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'NoHojaRuta', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'basico', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'conIncremento', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'turnopartido', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'confronta', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'voluntario', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'totalHoras', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'cantidadViajes', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'cantidadSalidas', '' . "\0" . 'AppBundle\\Entity\\HojaRuta' . "\0" . 'fecha', 'turno', 'omnibus', 'recaudaciones', 'ruta', 'incidencia_hr');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HojaRuta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addRecaudacione(\AppBundle\Entity\Recaudacion $recaudacione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecaudacione', array($recaudacione));

        return parent::addRecaudacione($recaudacione);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecaudacione(\AppBundle\Entity\Recaudacion $recaudacione)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecaudacione', array($recaudacione));

        return parent::removeRecaudacione($recaudacione);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getIncidenciaHr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncidenciaHr', array());

        return parent::getIncidenciaHr();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncidenciaHr($incidencia_hr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncidenciaHr', array($incidencia_hr));

        return parent::setIncidenciaHr($incidencia_hr);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoHojaRuta($NoHojaRuta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoHojaRuta', array($NoHojaRuta));

        return parent::setNoHojaRuta($NoHojaRuta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoHojaRuta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoHojaRuta', array());

        return parent::getNoHojaRuta();
    }

    /**
     * {@inheritDoc}
     */
    public function setBasico($basico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBasico', array($basico));

        return parent::setBasico($basico);
    }

    /**
     * {@inheritDoc}
     */
    public function getBasico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBasico', array());

        return parent::getBasico();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadSalidas($cantidadSalidas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadSalidas', array($cantidadSalidas));

        return parent::setCantidadSalidas($cantidadSalidas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadSalidas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadSalidas', array());

        return parent::getCantidadSalidas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadViajes($cantidadViajes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadViajes', array($cantidadViajes));

        return parent::setCantidadViajes($cantidadViajes);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadViajes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadViajes', array());

        return parent::getCantidadViajes();
    }

    /**
     * {@inheritDoc}
     */
    public function setConIncremento($conIncremento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConIncremento', array($conIncremento));

        return parent::setConIncremento($conIncremento);
    }

    /**
     * {@inheritDoc}
     */
    public function getConIncremento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConIncremento', array());

        return parent::getConIncremento();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfronta($confronta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfronta', array($confronta));

        return parent::setConfronta($confronta);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfronta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfronta', array());

        return parent::getConfronta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', array($observaciones));

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', array());

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmnibus($omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmnibus', array($omnibus));

        return parent::setOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmnibus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmnibus', array());

        return parent::getOmnibus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecaudaciones($recaudaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecaudaciones', array($recaudaciones));

        return parent::setRecaudaciones($recaudaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecaudaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecaudaciones', array());

        return parent::getRecaudaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuta($ruta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuta', array($ruta));

        return parent::setRuta($ruta);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuta', array());

        return parent::getRuta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalHoras($totalHoras)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalHoras', array($totalHoras));

        return parent::setTotalHoras($totalHoras);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalHoras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalHoras', array());

        return parent::getTotalHoras();
    }

    /**
     * {@inheritDoc}
     */
    public function setTurno($turno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurno', array($turno));

        return parent::setTurno($turno);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurno', array());

        return parent::getTurno();
    }

    /**
     * {@inheritDoc}
     */
    public function setTurnopartido($turnopartido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTurnopartido', array($turnopartido));

        return parent::setTurnopartido($turnopartido);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurnopartido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurnopartido', array());

        return parent::getTurnopartido();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoluntario($voluntario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoluntario', array($voluntario));

        return parent::setVoluntario($voluntario);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoluntario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoluntario', array());

        return parent::getVoluntario();
    }

}
