<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chofer extends \AppBundle\Entity\Chofer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'licencia_emision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'licencia_vencimiento', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'noLicenciaOperativa', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'recalificacion_emision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'recalificacionVencimiento', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenMedicoEmision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenMedicoVencimiento', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenPsicofisiologicoEmision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenPsicofisiologicoVencimiento', 'omnibus', 'escogida', 'trabajador');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'licencia_emision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'licencia_vencimiento', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'noLicenciaOperativa', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'recalificacion_emision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'recalificacionVencimiento', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenMedicoEmision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenMedicoVencimiento', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenPsicofisiologicoEmision', '' . "\0" . 'AppBundle\\Entity\\Chofer' . "\0" . 'examenPsicofisiologicoVencimiento', 'omnibus', 'escogida', 'trabajador');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Chofer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addEscogida(\AppBundle\Entity\EscogidaTurno $escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEscogida', array($escogida));

        return parent::addEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEscogida(\AppBundle\Entity\EscogidaTurno $escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEscogida', array($escogida));

        return parent::removeEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function setEscogida($escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscogida', array($escogida));

        return parent::setEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscogida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscogida', array());

        return parent::getEscogida();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamenMedicoEmision($examenMedicoEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamenMedicoEmision', array($examenMedicoEmision));

        return parent::setExamenMedicoEmision($examenMedicoEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamenMedicoEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamenMedicoEmision', array());

        return parent::getExamenMedicoEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamenMedicoVencimiento($examenMedicoVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamenMedicoVencimiento', array($examenMedicoVencimiento));

        return parent::setExamenMedicoVencimiento($examenMedicoVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamenMedicoVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamenMedicoVencimiento', array());

        return parent::getExamenMedicoVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamenPsicofisiologicoEmision($examenPsicofisiologicoEmision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamenPsicofisiologicoEmision', array($examenPsicofisiologicoEmision));

        return parent::setExamenPsicofisiologicoEmision($examenPsicofisiologicoEmision);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamenPsicofisiologicoEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamenPsicofisiologicoEmision', array());

        return parent::getExamenPsicofisiologicoEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamenPsicofisiologicoVencimiento($examenPsicofisiologicoVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamenPsicofisiologicoVencimiento', array($examenPsicofisiologicoVencimiento));

        return parent::setExamenPsicofisiologicoVencimiento($examenPsicofisiologicoVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamenPsicofisiologicoVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamenPsicofisiologicoVencimiento', array());

        return parent::getExamenPsicofisiologicoVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenciaEmision($licencia_emision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenciaEmision', array($licencia_emision));

        return parent::setLicenciaEmision($licencia_emision);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenciaEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenciaEmision', array());

        return parent::getLicenciaEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenciaVencimiento($licencia_vencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenciaVencimiento', array($licencia_vencimiento));

        return parent::setLicenciaVencimiento($licencia_vencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenciaVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenciaVencimiento', array());

        return parent::getLicenciaVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoLicenciaOperativa($noLicenciaOperativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoLicenciaOperativa', array($noLicenciaOperativa));

        return parent::setNoLicenciaOperativa($noLicenciaOperativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoLicenciaOperativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoLicenciaOperativa', array());

        return parent::getNoLicenciaOperativa();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmnibus($omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmnibus', array($omnibus));

        return parent::setOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmnibus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmnibus', array());

        return parent::getOmnibus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecalificacionVencimiento($recalificacionVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecalificacionVencimiento', array($recalificacionVencimiento));

        return parent::setRecalificacionVencimiento($recalificacionVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecalificacionVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecalificacionVencimiento', array());

        return parent::getRecalificacionVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecalificacionEmision($recalificacion_emision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecalificacionEmision', array($recalificacion_emision));

        return parent::setRecalificacionEmision($recalificacion_emision);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecalificacionEmision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecalificacionEmision', array());

        return parent::getRecalificacionEmision();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrabajador($trabajador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrabajador', array($trabajador));

        return parent::setTrabajador($trabajador);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajador', array());

        return parent::getTrabajador();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

}
