<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ruta extends \AppBundle\Entity\Ruta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'noruta', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'distanciakm', 'hojaruta', 'escogida', 'dias', 'expedicion', 'servicio', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'cantpasajerospromedio', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'salida', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'destino', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'frecuencia', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'recaudacion', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'cantidadmedios', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'preciopasaje', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'cantdiassemana_trabajo');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'noruta', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'distanciakm', 'hojaruta', 'escogida', 'dias', 'expedicion', 'servicio', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'cantpasajerospromedio', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'salida', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'destino', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'frecuencia', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'recaudacion', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'cantidadmedios', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'preciopasaje', '' . "\0" . 'AppBundle\\Entity\\Ruta' . "\0" . 'cantdiassemana_trabajo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ruta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addHojaRutum(\AppBundle\Entity\HojaRuta $hojarutum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHojaRutum', array($hojarutum));

        return parent::addHojaRutum($hojarutum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHojaRutum(\AppBundle\Entity\HojaRuta $hojarutum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHojaRutum', array($hojarutum));

        return parent::removeHojaRutum($hojarutum);
    }

    /**
     * {@inheritDoc}
     */
    public function addDia(\AppBundle\Entity\DiasSemana $dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDia', array($dia));

        return parent::addDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDia(\AppBundle\Entity\DiasSemana $dia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDia', array($dia));

        return parent::removeDia($dia);
    }

    /**
     * {@inheritDoc}
     */
    public function addServicio(\AppBundle\Entity\Servicio $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServicio', array($servicio));

        return parent::addServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServicio(\AppBundle\Entity\Servicio $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServicio', array($servicio));

        return parent::removeServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function addEscogida(\AppBundle\Entity\EscogidaTurno $escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEscogida', array($escogida));

        return parent::addEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEscogida(\AppBundle\Entity\EscogidaTurno $escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEscogida', array($escogida));

        return parent::removeEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoruta($noruta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoruta', array($noruta));

        return parent::setNoruta($noruta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoruta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoruta', array());

        return parent::getNoruta();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantdiassemanaTrabajo($cantdiassemana_trabajo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantdiassemanaTrabajo', array($cantdiassemana_trabajo));

        return parent::setCantdiassemanaTrabajo($cantdiassemana_trabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantdiassemanaTrabajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantdiassemanaTrabajo', array());

        return parent::getCantdiassemanaTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadmedios($cantidadmedios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadmedios', array($cantidadmedios));

        return parent::setCantidadmedios($cantidadmedios);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadmedios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadmedios', array());

        return parent::getCantidadmedios();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantpasajerospromedio($cantpasajerospromedio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantpasajerospromedio', array($cantpasajerospromedio));

        return parent::setCantpasajerospromedio($cantpasajerospromedio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantpasajerospromedio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantpasajerospromedio', array());

        return parent::getCantpasajerospromedio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestino($destino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestino', array($destino));

        return parent::setDestino($destino);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestino', array());

        return parent::getDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setDias($dias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDias', array($dias));

        return parent::setDias($dias);
    }

    /**
     * {@inheritDoc}
     */
    public function getDias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDias', array());

        return parent::getDias();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicio($servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicio', array($servicio));

        return parent::setServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicio', array());

        return parent::getServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistanciakm($distanciakm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistanciakm', array($distanciakm));

        return parent::setDistanciakm($distanciakm);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistanciakm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistanciakm', array());

        return parent::getDistanciakm();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscogida($escogida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscogida', array($escogida));

        return parent::setEscogida($escogida);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscogida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscogida', array());

        return parent::getEscogida();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpedicion($expedicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpedicion', array($expedicion));

        return parent::setExpedicion($expedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpedicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpedicion', array());

        return parent::getExpedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrecuencia($frecuencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrecuencia', array($frecuencia));

        return parent::setFrecuencia($frecuencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrecuencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrecuencia', array());

        return parent::getFrecuencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setHojaruta($hojaruta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHojaruta', array($hojaruta));

        return parent::setHojaruta($hojaruta);
    }

    /**
     * {@inheritDoc}
     */
    public function getHojaruta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHojaruta', array());

        return parent::getHojaruta();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreciopasaje($preciopasaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreciopasaje', array($preciopasaje));

        return parent::setPreciopasaje($preciopasaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreciopasaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreciopasaje', array());

        return parent::getPreciopasaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecaudacion($recaudacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecaudacion', array($recaudacion));

        return parent::setRecaudacion($recaudacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecaudacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecaudacion', array());

        return parent::getRecaudacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalida($salida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalida', array($salida));

        return parent::setSalida($salida);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalida', array());

        return parent::getSalida();
    }

}
