<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tarjeta_combustible extends \AppBundle\Entity\Tarjeta_combustible implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'asignacion', 'combustibleTipo', 'omnibus', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'gastoReal', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'fechaVencimiento', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'fechaAsignacion', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'tipoCombustible', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'saldoActual', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'noTarjeta', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'ping');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'asignacion', 'combustibleTipo', 'omnibus', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'gastoReal', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'fechaVencimiento', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'fechaAsignacion', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'tipoCombustible', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'saldoActual', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'noTarjeta', '' . "\0" . 'AppBundle\\Entity\\Tarjeta_combustible' . "\0" . 'ping');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tarjeta_combustible $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addOmnibus(\AppBundle\Entity\Omnibus $omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOmnibus', array($omnibus));

        return parent::addOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOmnibus(\AppBundle\Entity\Omnibus $omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOmnibus', array($omnibus));

        return parent::removeOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function addCombustibleTipo(\AppBundle\Entity\TipoCombustible $combustibleTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCombustibleTipo', array($combustibleTipo));

        return parent::addCombustibleTipo($combustibleTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCombustibleTipo(\AppBundle\Entity\TipoCombustible $combustibleTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCombustibleTipo', array($combustibleTipo));

        return parent::removeCombustibleTipo($combustibleTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignacion', array());

        return parent::getAsignacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsignacion($asignacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsignacion', array($asignacion));

        return parent::setAsignacion($asignacion);
    }

    /**
     * {@inheritDoc}
     */
    public function setCombustibleTipo($combustibleTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCombustibleTipo', array($combustibleTipo));

        return parent::setCombustibleTipo($combustibleTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCombustibleTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCombustibleTipo', array());

        return parent::getCombustibleTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAsignacion($fechaAsignacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAsignacion', array($fechaAsignacion));

        return parent::setFechaAsignacion($fechaAsignacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAsignacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAsignacion', array());

        return parent::getFechaAsignacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaVencimiento($fechaVencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaVencimiento', array($fechaVencimiento));

        return parent::setFechaVencimiento($fechaVencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaVencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaVencimiento', array());

        return parent::getFechaVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setGastoReal($gastoReal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGastoReal', array($gastoReal));

        return parent::setGastoReal($gastoReal);
    }

    /**
     * {@inheritDoc}
     */
    public function getGastoReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGastoReal', array());

        return parent::getGastoReal();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoTarjeta($noTarjeta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoTarjeta', array($noTarjeta));

        return parent::setNoTarjeta($noTarjeta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoTarjeta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoTarjeta', array());

        return parent::getNoTarjeta();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmnibus($omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmnibus', array($omnibus));

        return parent::setOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmnibus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmnibus', array());

        return parent::getOmnibus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPing($ping)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPing', array($ping));

        return parent::setPing($ping);
    }

    /**
     * {@inheritDoc}
     */
    public function getPing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPing', array());

        return parent::getPing();
    }

    /**
     * {@inheritDoc}
     */
    public function setSaldoActual($saldoActual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSaldoActual', array($saldoActual));

        return parent::setSaldoActual($saldoActual);
    }

    /**
     * {@inheritDoc}
     */
    public function getSaldoActual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSaldoActual', array());

        return parent::getSaldoActual();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoCombustible($tipoCombustible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoCombustible', array($tipoCombustible));

        return parent::setTipoCombustible($tipoCombustible);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoCombustible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoCombustible', array());

        return parent::getTipoCombustible();
    }

}
