<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tipo_omnibus extends \AppBundle\Entity\Tipo_omnibus implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'desviacion', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'indiceConsumoNormado', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'cantidadKmtsXlitro', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'capacidad_total', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'capacidad_sentados', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'capacidad_parados', 'omnibus');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'desviacion', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'indiceConsumoNormado', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'cantidadKmtsXlitro', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'capacidad_total', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'capacidad_sentados', '' . "\0" . 'AppBundle\\Entity\\Tipo_omnibus' . "\0" . 'capacidad_parados', 'omnibus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tipo_omnibus $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addOmnibus(\AppBundle\Entity\Omnibus $omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOmnibus', array($omnibus));

        return parent::addOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOmnibus(\AppBundle\Entity\Omnibus $omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOmnibus', array($omnibus));

        return parent::removeOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadKmtsXlitro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadKmtsXlitro', array());

        return parent::getCantidadKmtsXlitro();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadKmtsXlitro($cantidadKmtsXlitro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadKmtsXlitro', array($cantidadKmtsXlitro));

        return parent::setCantidadKmtsXlitro($cantidadKmtsXlitro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidadParados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidadParados', array());

        return parent::getCapacidadParados();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacidadParados($capacidad_parados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacidadParados', array($capacidad_parados));

        return parent::setCapacidadParados($capacidad_parados);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidadSentados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidadSentados', array());

        return parent::getCapacidadSentados();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacidadSentados($capacidad_sentados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacidadSentados', array($capacidad_sentados));

        return parent::setCapacidadSentados($capacidad_sentados);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidadTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidadTotal', array());

        return parent::getCapacidadTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacidadTotal($capacidad_total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacidadTotal', array($capacidad_total));

        return parent::setCapacidadTotal($capacidad_total);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesviacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesviacion', array());

        return parent::getDesviacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesviacion($desviacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesviacion', array($desviacion));

        return parent::setDesviacion($desviacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndiceConsumoNormado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndiceConsumoNormado', array());

        return parent::getIndiceConsumoNormado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndiceConsumoNormado($indiceConsumoNormado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndiceConsumoNormado', array($indiceConsumoNormado));

        return parent::setIndiceConsumoNormado($indiceConsumoNormado);
    }

    /**
     * {@inheritDoc}
     */
    public function getOmnibus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOmnibus', array());

        return parent::getOmnibus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOmnibus($omnibus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOmnibus', array($omnibus));

        return parent::setOmnibus($omnibus);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

}
